apiVersion: v2
name: potoo
description: A local dev chart for Airflow

type: application

version: 0.0.1
appVersion: "1.0.0"

dependencies:
  - name: airflow
    version: 1.6.0
    repository: https://airflow.apache.org/

  - name: superset
    version: 0.7.4
    repository: http://apache.github.io/superset/

  - name: postgresql
    version: 12.1.0
    repository: https://charts.bitnami.com/bitnami