"""init_users

Revision ID: 2557074a6ddb
Revises: 
Create Date: 2022-10-16 12:36:00.679356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2557074a6ddb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_users_id'), 'promo_users', ['id'], unique=False)
    op.create_index(op.f('ix_promo_users_user_id'), 'promo_users', ['user_id'], unique=True)
    op.create_table('seed_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('promo_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['promo_user_id'], ['promo_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_seed_users_promo_user_id'), 'seed_users', ['promo_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seed_users_promo_user_id'), table_name='seed_users')
    op.drop_table('seed_users')
    op.drop_index(op.f('ix_promo_users_user_id'), table_name='promo_users')
    op.drop_index(op.f('ix_promo_users_id'), table_name='promo_users')
    op.drop_table('promo_users')
    # ### end Alembic commands ###
