"""init_users

Revision ID: 91ffafaac82b
Revises: 2557074a6ddb
Create Date: 2022-10-16 12:40:05.285663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ffafaac82b'
down_revision = '2557074a6ddb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
