"""Added

Revision ID: a9ae904938d0
Revises: 7e3625ed3513
Create Date: 2022-10-16 11:55:46.764700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ae904938d0'
down_revision = '7e3625ed3513'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_users', sa.Column('added_at', sa.DateTime(), nullable=True))
    op.add_column('seed_users', sa.Column('added_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seed_users', 'added_at')
    op.drop_column('promo_users', 'added_at')
    # ### end Alembic commands ###
